### ISSUE TITLE
FR12. Previous Searches

### ISSUE THREAD

**Issue by PattyCoding123** [WSU-4110/Degree-Door#17]
|FR12. Previous Searches|
|---|
|**Goal**: Save the most recent search in the search menu bar.
**Stakeholders:** Upcoming Students, Current Students, Alumni, Professors|
| **Description:** After searching for a degree in the search bar the system will save your 3 most recent searches for quick access in case of interruption, crash, or disconnect from the internet.|
| **Origin:** DegreeDoor members decided on this requirement during the first Software Requirements meeting.|
| **Version:** 1.0  |  
|**Date:** 9/20/2022
|  **Priority:** 3 |

**Comment by Greysushii** [comment]
Closed due to the extensive work need to integrate cookies to allow the search bar to recall previous searches. Wasn't enough time to implement.
